### ISSUE TITLE
Deprecated Methods?

### ISSUE THREAD

**Issue by StNebel** [akashivskyy/GoogleAnalytics-Framework#16]
@akashivskyy 
In order to use this framework for all iOS versions in future, I need a statement as to whether deprecated such as 
`[general] 'NSKeyedUnarchiveFromData' should not be used to for un-archiving and will be removed in a future release`
 are used.
see: https://developer.apple.com/documentation/foundation/nskeyedunarchiver/1413894-unarchiveobject

**Comment by akashivskyy** [comment]
Hi there! I don't work for Google and I don't work on Google Analytics SDK. This is not an official Google Analytics distribution. This project just repackages [Google Analytics binary](https://developers.google.com/analytics/devguides/collection/ios/v3/) in a format recognizable by Carthage. I don't even use the framework myself anymore. In fact, I'm going to archive this repository since I no longer have time or will to maintain it, so I recommend against using it.

I recommend you [contact Google's support](https://developers.google.com/analytics/devguides/collection/ios/v3/help) as they are the ones that can actually fix the issue.

Cheers! 🙌
