### ISSUE TITLE
Question of implementation

### ISSUE THREAD

**Issue by tuxtux59** [akashivskyy/GoogleAnalytics-Framework#6]
Hi,
I would like to know how to implement your library.
I've downloading the .plist file from google analytics page and I would like to know if your library just override the pod install or it needs special config to use it?
In fact my question is : It's still google implementation(draging .plist to project and write into Appdelegate) or something else?

Thanks

**Comment by akashivskyy** [comment]
This project just wraps Google's static library in a `.framework` module so that you can import it directly in Swift using `import GoogleAnalytics` without the need to create a bridging header. You can even check SHA1 checksum of `libGoogleAnalyticsServices.a` file – it's same as Google's.

To answer your specific question: Yes, it's exactly the same in functionality, just different in distribution.

**Comment by akashivskyy** [comment]
@tuxtux59 Did that answer your question?

**Comment by tuxtux59** [comment]
Yes, thanks. I added the framework in General Tab on project view and used it as you explained ! thanks
